modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/dodogang/architectury-example-mod/issues"
license = "Insert License Here"

[[mods]]
modId = "examplemod"
version = "${version}"
displayName = "Example Mod"
#updateJSONURL = ""
displayURL = "https://github.com/dodogang/architectury-example-mod"
#credits = ""
authors = "Dodo Gang"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"