modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/trikzon/pitch-dark/issues"
license = "MIT; Assets licensed as All Rights Reserved"

[[mods]]
modId = "pitch-dark"
version = "${version}"
displayName = "Pitch Dark"
#updateJSONURL = ""
displayURL = "https://github.com/trikzon/pitch-dark"
#credits = ""
authors = "Trikzon"
description = '''
Only allow hostile mobs to spawn in complete darkness
'''
#logoFile = ""

[[dependencies.pitch-dark]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pitch-dark]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"